export const COMPLIANCE_CODES = {
  COMPANY_NAME_MISSING: 'COMPANY_NAME_MISSING',
  COMPANY_ADDRESS_MISSING: 'COMPANY_ADDRESS_MISSING',
  COMPANY_POSTAL_CODE_MISSING: 'COMPANY_POSTAL_CODE_MISSING',
  COMPANY_CITY_MISSING: 'COMPANY_CITY_MISSING',
  COMPANY_COUNTRY_MISSING: 'COMPANY_COUNTRY_MISSING',
  COMPANY_SIREN_MISSING: 'COMPANY_SIREN_MISSING',
  COMPANY_SIRET_MISSING: 'COMPANY_SIRET_MISSING',
  COMPANY_VAT_MISSING: 'COMPANY_VAT_MISSING',

  CLIENT_NAME_MISSING: 'CLIENT_NAME_MISSING',
  CLIENT_ADDRESS_MISSING: 'CLIENT_ADDRESS_MISSING',
  CLIENT_POSTAL_CODE_MISSING: 'CLIENT_POSTAL_CODE_MISSING',
  CLIENT_CITY_MISSING: 'CLIENT_CITY_MISSING',
  CLIENT_COUNTRY_MISSING: 'CLIENT_COUNTRY_MISSING',

  CLIENT_SIREN_MISSING: 'CLIENT_SIREN_MISSING',
  CLIENT_SIRET_MISSING: 'CLIENT_SIRET_MISSING',

  INVOICE_NUMBER_MISSING: 'INVOICE_NUMBER_MISSING',
  INVOICE_DATE_MISSING: 'INVOICE_DATE_MISSING',
  INVOICE_CURRENCY_MISSING: 'INVOICE_CURRENCY_MISSING',
  INVOICE_AMOUNT_INVALID: 'INVOICE_AMOUNT_INVALID',
  INVOICE_SUBTOTAL_INVALID: 'INVOICE_SUBTOTAL_INVALID',
  INVOICE_VAT_AMOUNT_INVALID: 'INVOICE_VAT_AMOUNT_INVALID',

  INVOICE_ITEMS_MISSING: 'INVOICE_ITEMS_MISSING',

  ITEM_DESCRIPTION_MISSING: 'ITEM_DESCRIPTION_MISSING',
  ITEM_QUANTITY_INVALID: 'ITEM_QUANTITY_INVALID',
  ITEM_UNIT_PRICE_INVALID: 'ITEM_UNIT_PRICE_INVALID',
  ITEM_TOTAL_INVALID: 'ITEM_TOTAL_INVALID',
  ITEM_VAT_RATE_INVALID: 'ITEM_VAT_RATE_INVALID',

  DELIVERY_ADDRESS_INCOMPLETE: 'DELIVERY_ADDRESS_INCOMPLETE',

  PRECEDING_INVOICE_MISSING: 'PRECEDING_INVOICE_MISSING',

  COUNTRY_WARNING: 'COUNTRY_WARNING',
} as const;